build out skeleton of components for app with hard coded placeholders
jturgeon88/mini-netflix pull request #1
Opened 2019-08-27 16:25 UTC by jturgeon88

2019-08-27 16:55 UTC, b-wils requested changes
Code looks good, good separation of components.

2019-08-27 16:55 UTC, b-wils commented on src/lib/fetchMovies.js
> +export const fetchResults = () => {
For a file with a single export it is good practice to

1. Use default export instead of named export
2. Internal function name to match the file name

Alternatively could have a lib that does multiple functions. ie: movieApi.js; export {fetchMovies, fetchMovieByName, etc.}

2019-08-27 16:55 UTC, b-wils commented on src/lib/fetchMovies.js
> +  return fetch(url)
Consider using Axios instead of fetch

2019-08-27 16:55 UTC, b-wils commented on src/lib/fetchMovies.js
> +// // Fetch single movie object by specific movie title
Try not to check in commented out code. Either save for next checkin, uncomment or in certain cases put a comment about why it doesn't work now but may be useful later.

2019-08-27 16:55 UTC, b-wils commented on src/components/MovieTile.js
> +const MovieTile = props => {
Try using object destructuring on props to clean up code

2019-08-27 16:55 UTC, b-wils commented on src/components/MovieRow.js
> +    console.log('movies', this.state.movies);
Dont checkin console.log

2019-08-27 16:55 UTC, b-wils commented on src/components/Home.js
> +const movies = [
Choose a more descriptive name, maybe movie categories?

2019-08-27 16:55 UTC, b-wils commented on src/components/MovieDetails.js
> +const MovieDetails = props => {
Use object destructuring to get your props

2019-08-27 16:55 UTC, b-wils commented on src/lib/fetchMovies.js
> +  const url = `https://api.themoviedb.org/3/movie/upcoming?api_key=4d607e131c52e3c7b3f49a1eed738529&language=en-US&page=1`;
Consider adding a url builder for requests to the movies api. That way your request calls only need to pass in their relative path and data specific to the request.

Also don't commit API key. CRA should have support for .env files. Make sure to document how a new developer would configure their .env.

2019-08-27 19:34 UTC, jturgeon88 commented on src/lib/fetchMovies.js
> +  return fetch(url)
Done

2019-08-27 19:35 UTC, jturgeon88 commented on src/lib/fetchMovies.js
> +// // Fetch single movie object by specific movie title
Yuup. Done

2019-08-27 19:37 UTC, jturgeon88 commented on src/components/MovieRow.js
> +    console.log('movies', this.state.movies);
Done

2019-08-27 19:37 UTC, jturgeon88 commented on src/lib/fetchMovies.js
> +export const fetchResults = () => {
Done

2019-08-27 19:53 UTC, jturgeon88 commented on src/components/MovieTile.js
> +const MovieTile = props => {
Done.

2019-08-27 19:54 UTC, jturgeon88 commented on src/components/Home.js
> +const movies = [
Done.

2019-08-27 20:13 UTC, jturgeon88 commented on src/components/MovieDetails.js
> +const MovieDetails = props => {
Done.

2019-08-27 21:11 UTC, jturgeon88 commented on src/lib/fetchMovies.js
> +  const url = `https://api.themoviedb.org/3/movie/upcoming?api_key=4d607e131c52e3c7b3f49a1eed738529&language=en-US&page=1`;
Done

2019-08-28 15:04 UTC, b-wils requested changes

2019-08-28 15:04 UTC, b-wils commented on src/lib/movieApi.js
> +      queryParams: '&language=en-US&page=1'
Can you break this into an object instead of string:

{
language: 'en-US',
page: 1
}

2019-08-28 15:04 UTC, b-wils commented on src/lib/movieApi.js
> +  return axios({
Is it possible to pass the axiosOpt you received instead of making a new object? You would have to add the global fields (baseUrl, params.api_key)

2019-08-28 15:04 UTC, b-wils commented on src/lib/movieApi.js
>      .then(response => {
I believe Axios already throws an error if the request fails.

2019-08-28 15:04 UTC, b-wils commented on src/lib/movieApi.js
> +  return axios({
Now that I think about it we shouldn't mutate our function arguments. The starting point of our new object should be AxiosOpt though, in case a caller wants to use more advanced axios options.

2019-08-28 15:43 UTC, b-wils approved these changes

2019-08-28 15:45 UTC, merged