Movie row
jturgeon88/mini-netflix pull request #3
Opened 2019-08-28 20:44 UTC by jturgeon88

2019-08-28 22:50 UTC, b-wils requested changes

2019-08-28 22:50 UTC, b-wils commented on src/components/MovieRow.js
> +    this.fetchMovies(() => fetchMovies(category.url, category.searchTitle));
You have two functions named fetchMovies(). One from class and one from the api. This makes them hard to distinguish. Consider renaming them or changing your import (import * as movieApi from '../lib/movieApi';).

2019-08-28 22:50 UTC, b-wils commented on src/components/MovieTile.js
> +  const PosterComp = styled.img`
Creating styled components inside a render function will cause a new instance to be allocated on each render. Create new styled components at the top level.

2019-08-28 22:50 UTC, b-wils commented on src/components/MovieRow.js
> +    this.fetchMovies(() => fetchMovies(category.url, category.searchTitle));
What is the final request path? How does category.searchTitle map to a parameter?

2019-08-29 16:28 UTC, jturgeon88 commented on src/components/MovieTile.js
> +  const PosterComp = styled.img`
Done. Moved to top level.

2019-08-29 16:35 UTC, jturgeon88 commented on src/components/MovieRow.js
> +    this.fetchMovies(() => fetchMovies(category.url, category.searchTitle));
Resolved.

2019-08-29 17:00 UTC, b-wils commented on src/components/Home.js
> +        {movieCategories.map((category, index) => <MovieRow key={index} category={category} />)}
It is bad practice to use index as a key. The index is not tied to a category, so if the categories change we will get inconsistent results. Ideally we would have an id from the database. Can we use a field from category?

2019-08-29 17:00 UTC, b-wils commented on src/components/MovieRow.js
> +        <div className="movie-row">{this.state.movies.map((movie, index) => <MovieTile key={index} movie={movie} />)}</div>
See above on index as a key

2019-08-29 20:25 UTC, b-wils approved these changes

2019-08-29 20:25 UTC, merged